### ISSUE TITLE
TypeError on initial install.

### ISSUE THREAD

**Issue by giodamelio** [nuxt-community/content-template#7] opened 2017-08-31 19:58 UTC
When I created a fresh project using the `vue-cli` command, the first thing I get after I run `yarn build` then `yarn start` is an `TypeError`.

```
Nuxt.js Error:

TypeError: inject is not a function
    at module.exports.__webpack_exports__.default (server-bundle.js:1373:3)
    at _callee$ (server-bundle.js:1088:20)
    at tryCatch (/home/giodamelio/tmp/nuxtent-test/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/giodamelio/tmp/nuxtent-test/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/giodamelio/tmp/nuxtent-test/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (server-bundle.js:228:30)
    at server-bundle.js:239:13
    at <anonymous>
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c5">#c5</a>)</em></sub></div>

**Comment by giodamelio** [comment] 2017-08-31 20:13
The same error also happens when I run `yarn generate`. Though it does give a bit more information.

```
... snip build output ...

  nuxt:generate Destination folder cleaned +12s
  nuxt:generate Static & build files copied +10ms
  nuxt:render Rendering url / +3ms
  nuxt:generate HTML Files generated in 12.2s +39ms
==== Error report ==== 
Route: '/'
TypeError: inject is not a function
    at module.exports.__webpack_exports__.default (server-bundle.js:1373:3)
    at _callee$ (server-bundle.js:1088:20)
    at tryCatch (/home/giodamelio/tmp/nuxtent-test/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/giodamelio/tmp/nuxtent-test/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/giodamelio/tmp/nuxtent-test/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (server-bundle.js:228:30)
    at server-bundle.js:239:13
    at <anonymous>
[nuxt] Generate done
Done in 15.78s.
```

**Comment by giodamelio** [comment] 2017-08-31 20:49
It turns out that updating the `nuxt` version to `^1.0.0-rc8` and running `nuxt build` fixes this problem.

**Comment by alidcast** [comment] 2017-08-31 21:04
Yes, not sure what the cause of the above error is but glad that updating Nuxt got it to work! 

Thanks for the update. I'll go ahead and close this, feel free to open a new issue if you experience any problems.

**Closed as completed by alidcast** 2017-08-31 21:04 UTC
